# Generated by Django 3.1.5 on 2021-03-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUploader',
        ),
    ]
