# Generated by Django 3.1.5 on 2021-03-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.TextField(max_length=200),
        ),
    ]
