# Generated by Django 3.1.5 on 2021-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
