# Generated by Django 3.1.5 on 2021-03-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_user_desc'),
    ]

    operations = [
        migrations.RenameModel('User','hello')
    ]
