# Generated by Django 3.1.5 on 2021-03-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20210324_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
