# Generated by Django 3.1.5 on 2021-03-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20210324_1843'),
    ]

    operations = [
        migrations.RenameModel('hello','ImageUploader')
    ]
