# Generated by Django 3.1.5 on 2021-03-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_auto_20210324_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploader',
            name='name',
        ),
    ]
